// <auto-generated />
using System;
using GestionAdherentsClub.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GestionAdherentsClub.Migrations
{
    [DbContext(typeof(AdherentContext))]
    [Migration("20240426104800_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("GestionAdherentsClub.Models.Adherent", b =>
                {
                    b.Property<int>("AdherentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AdherentId"));

                    b.Property<string>("AdherentAdresse")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("AdherentDateNaissance")
                        .HasColumnType("datetime2");

                    b.Property<string>("AdherentName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ClubID")
                        .HasColumnType("int");

                    b.HasKey("AdherentId");

                    b.HasIndex("ClubID");

                    b.ToTable("Adherents");
                });

            modelBuilder.Entity("GestionAdherentsClub.Models.Club", b =>
                {
                    b.Property<int>("ClubID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ClubID"));

                    b.Property<string>("ClubName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClubNomResponsable")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ClubID");

                    b.ToTable("Clubs");
                });

            modelBuilder.Entity("GestionAdherentsClub.Models.Adherent", b =>
                {
                    b.HasOne("GestionAdherentsClub.Models.Club", "Club")
                        .WithMany("Adherents")
                        .HasForeignKey("ClubID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Club");
                });

            modelBuilder.Entity("GestionAdherentsClub.Models.Club", b =>
                {
                    b.Navigation("Adherents");
                });
#pragma warning restore 612, 618
        }
    }
}
